Fixed problem in compilation: [gwt.javac] D:\gwt-ext\ux\trunk\samples\showcase2\src\com\gwtextux\sample\showcase2\server\LiveGridDataProxy.java:82: incompatible types [gwt.javac] found : java.lang.Object [gwt.javac] required: java.lang.Object[][] [gwt.javac] LiveGridDataProxy.data=data.clone(); [gwt.javac] ^ [gwt.javac] 1 error